[package]
name = "microservice-comparison-rust"
version = "0.0.1"
authors = ["Stephen Solka <stephen0q@gmail.com>"]

[dependencies]
reqwest = "0.11.13"
json = "0.12.4"
actix-web = "4.2.1"
futures = "0.3.25"